### ISSUE TITLE
Delete second chaosscon.md file ?

### ISSUE THREAD

**Issue by GeorgLink** [chaoss/community-handbook#10]
The repository has two `chaosscon.md` files:

1. https://github.com/chaoss/community-handbook/blob/master/chaosscon.md
2. https://github.com/chaoss/community-handbook/blob/master/community-initiatives/chaosscon.md

The [Handbook Page](https://app.gitbook.com/@chaoss-project/s/community-handbook/community-initiatives/chaosscon) seems to match file # 2.

Can we safely delete file # 1?

**Comment by jaskiratsingh2000** [comment]
Yes! We can delete the # 1. Seems like it wasn't synced properly.

**Comment by GeorgLink** [comment]
Thanks for the timely response. I opened PR #11 to fix this issue.
