### ISSUE TITLE
WG repository template

### ISSUE THREAD

**Issue by ritik-malik** [chaoss/community-handbook#15]
Hi,

Can someone point me to the *working group repository template*, that was shown in the last Community call.
Couldn't find it in the community-handbook...

**Comment by klumb** [comment]
Hi Maalik,

That is located in the CHAOSS Metrics Repo.

https://github.com/chaoss/metrics/blob/master/resources/metrics-template.md




On Mar 25, 2021, at 9:15 AM, maalik ***@***.******@***.***>> wrote:

Non-NU Email
________________________________



Hi,

Can someone point me to the working group repository template, that was shown in the last Community call.
Couldn't find it in the community-handbook...

**Comment by ritik-malik** [comment]
No not the metric template,

I'm talking about a template that defines the structure of an entire Working Group repository,
I recall someone saying in the last meeting that such a template does exist, but isn't being followed for now

**Comment by klumb** [comment]
To my knowledge, that repo structure template is a work in progress and is not official yet.

It is located in a google doc:
https://docs.google.com/document/d/1chPzgJa49sO_f3wVqp_NLJupSVyKHSVyuFuwzl4m4KI/edit#heading=h.4ejkic2mb7z1



On Mar 25, 2021, at 10:23 AM, maalik ***@***.******@***.***>> wrote:

Non-NU Email
________________________________



No not the metric template,

I'm talking about a template that defines the structure of an entire Working Group repository,
I recall someone saying in the last meeting that such a template does exist, but isn't being followed for now

**Comment by ritik-malik** [comment]
Ahh yes, this one,
Since I was trying the idea of [Automate Metrics Release and Process Improvement](https://github.com/chaoss/website/issues/537), I thought it would be a good idea to examine this template.
Will close this issue now

Thanks @klumb !
