### ISSUE TITLE
GitHub sync failed with GitBook

### ISSUE THREAD

**Issue by GeorgLink** [chaoss/community-handbook#21]
I merged [this draft](https://app.gitbook.com/@chaoss-project/s/community-handbook/~/drafts/-Mgz6Xkf9EDRS9nWuwo6/@activity) and then received an error message (screenshot below)

![Screen Shot 2021-08-13 at 1 15 36 PM](https://user-images.githubusercontent.com/8862021/129402141-28f7d365-0de8-49d7-ba90-e0be9dd2a025.png)

@jaskiratsingh2000, would you know how to restore the sync between GitBook and GitHub?

Thanks,
Georg

**Comment by jaskiratsingh2000** [comment]
Hi @GeorgLink This synchronization issue seems to be from the GitBook end. But you can find the restore option within the drafts

Thanks!

**Comment by GeorgLink** [comment]
Thanks @jaskiratsingh2000 ! The handbook is in the correct version on GitBook. I just need to get the changes over to GitHub. The documentation indicate that the timeout might be due to a large file. Maybe we need to split this page into smaller pages?

**Comment by GeorgLink** [comment]
I split the page into smaller pages and the synchronization succeeded.
