### ISSUE TITLE
Hyperlink in the word "repository" in main readme file does not serve any purpose

### ISSUE THREAD

**Issue by pratik2315** [chaoss/community-handbook#34]
The hyperlink repository directs back itself to the community-handbook repo. The sentence itself is self-explanatory and thus hyperlink serves no purpose. We should remove it?

![Screenshot (46)](https://user-images.githubusercontent.com/77961530/165914081-8b8e7e9b-6715-43d4-b620-1e58afba63b1.png)

**Comment by pratik2315** [comment]
this is my first time creating issue here😅 
correct me if im making any mistake

**Comment by yash2002109** [comment]
Hi @pratik2315,

Thanks for catching that. The `community-handbook` exists as sort of a source repository for the content. In my opinion, the content is meant to be consumed via the hosted Gitbook link -> https://handbook.chaoss.community/community-handbook/

![image](https://user-images.githubusercontent.com/77677278/166094779-e179793f-e5fd-43b5-8f00-c7eeb3b7c98d.png)

As you'll see the link fits in the above screenshot, I think we should leave it as it is for now.

**Comment by pratik2315** [comment]
Hmm makes sense. Thanks for the input @yash2002109 !
