### ISSUE TITLE
Reviews: D&I Badging Documentation 

### ISSUE THREAD

**Issue by xiaoya-Esther** [chaoss/community-handbook#5]
Please leave your comments under this issue for any advice about the current [D&I Badging Documentation](https://app.gitbook.com/@chaoss-project/s/community-handbook/initiative/overviewl)

Badging Documentation lives as a subgroup of the Community Handbook.

Every suggestion is tremendously valuable for us！😊

**Comment by GeorgLink** [comment]
Closing stale issue. Feel free to open again if there is a need for this issue.

Thank you @xiaoya-Esther, I appreciate all of your work on the D&I Badging Documentation.
