### ISSUE TITLE
Make file names meaningful

### ISSUE THREAD

**Issue by GeorgLink** [chaoss/community-handbook#8]
Some files have names like "[untitled-1.md](https://github.com/chaoss/community-handbook/blob/master/community-initiatives/untitled-1.md)"

It would be great to give each file a meaningful name so I can find the page I want to edit without having to try several different files.

Maybe it would even fix the URLs in GitBook, like https://handbook.chaoss.community/community-handbook/community-initiatives/untitled-1

How can we change the file names and URLS without disrupting the integration between GitHub and GitBook and breaking links within the handbook?

**Comment by jaskiratsingh2000** [comment]
Hi @GeorgLink 
This would be best edited through the GitBook. Below are the steps to resolve these issues:

- Open the Community-Handbook space in Gitbook
- Click on the page from the left navbar for which you want to fix the URL name. You would see three dots when you hover on to different options. Click on those three dots
- Once you click on the three dots you will have box coming out of the left navbar
- Under the field name "SLUG" add any relevant name of your choice

Once you mention a new name it will be reflected automatically in the URL. I have also attached the image below with the mark highlighted about the above steps. Let me know if this doesn't work for you, I would be glad to do that.

![CHAOSS_SCREENSHOT](https://user-images.githubusercontent.com/10228651/105730384-4e457b00-5f54-11eb-9178-5911c5251840.PNG)

**Comment by GeorgLink** [comment]
Thanks Jaskirat!

> Let me know if this doesn't work for you, I would be glad to do that

I assume it works and I would appreciate if you could update all filenames/URLs to be meaningful.

**Comment by jaskiratsingh2000** [comment]
Hi @GeorgLink 
I have updated all the pages filenames/URLs as per your suggestion. Feel free to check and let me know if any more changes required to be done. If everything is fine feel free to close the issue. :) Thanks!

**Comment by GeorgLink** [comment]
Thank you. Awesome work 👍
